version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus.yml
    ports:
      - "9090:9090"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
  alert:
    image: prom/alertmanager:latest
    container_name: alert-manager
    ports:
      - "9103:9103"
    volumes:
     - ./alert.yaml:/etc/alert.yaml
     
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
    restart: always
    networks:
      - monitor

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning

volumes:
  grafana-storage:
networks:
  monitor:
    driver: bridge
